language: go
dist: bionic
go:
    - 1.19

env:
  matrix:
    - TARGET=desktop
    - TARGET=rpi
before_install:
  - sudo snap install protobuf --classic
  - go install google.golang.org/protobuf/cmd/protoc-gen-go
  - go get -u google.golang.org/grpc
  - go mod download
  - mkdir messages
  - protoc -I protobuf_messages/ --go-grpc_out=messages --go_out=messages protobuf_messages/messages.proto

script:
  - if [ $TARGET == "desktop" ]; then
    go build;
    elif [ $TARGET == "rpi" ]; then
    env GOOS=linux GOARCH=arm GOARM=5 go build;
    fi
  - if [ $TARGET == "desktop" ]; then
    CI=true go test ./gpio_manager ./configuration_loader ./telegram_bot ./message_generator ./grpc_server ./rpi_client ./types -cover -race -timeout=10s;
    fi
