language: go
go:
    - 1.13.1

addons:
  apt:
    packages:
      - protobuf-compiler
script:
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - mkdir messages
    - protoc -I protobuf_messages/ --go_out=plugins=grpc:messages protobuf_messages/messages.proto
    - go build
    - go test ./... -cover
