language: go
dist: bionic
go:
    - 1.14

env:
  matrix:
    - TARGET=desktop
    - TARGET=rpi
before_install:
  - sudo snap install protobuf --classic
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go mod download
  - mkdir messages
  - protoc -I protobuf_messages/ --go_out=plugins=grpc:messages protobuf_messages/messages.proto

script:
  - if [ $TARGET == "desktop" ]; then
    go build;
    elif [ $TARGET == "rpi" ]; then
    env GOOS=linux GOARCH=arm GOARM=5 go build;
    fi
  - if [ $TARGET == "desktop" ]; then
    CI=true go test ./gpio_manager ./configuration_loader ./telegram_bot ./message_generator ./grpc_server ./grpc_client -cover -race -timeout=10s;
    fi
